version: '2'

services:
  httpd:
    image: httpd:latest
    volumes:
      - ./webroot:/usr/local/apache2/htdocs/
      - ./app:/usr/local/apache2/htdocs/app
      - ./node_modules:/usr/local/apache2/htdocs/node_modules
      - ./src:/usr/local/apache2/htdocs/src
    ports:
      - "80:80"
  npm:
    image: treyjones/npm:latest
    volumes:
      - ./:/npm
  tsc:
    image: treyjones/tsc:latest
    volumes:
      - ./:/tsc