version: '2'

services:
  tmoney:
    build:
      context: .
    container_name: tmoney
    volumes:
      - ./web:/home/app/web/
      - /home/app/web/node_modules
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"