/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../src/chart.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/core/src/linker/component_factory_resolver';
import * as import9 from './chart-sub.component.ngfactory';
import * as import10 from '../../src/chart-sub.component';
export class Wrapper_InfiniteChartComponent {
  /*private*/ _eventHandler:Function;
  context:import0.InfiniteChartComponent;
  /*private*/ _changed:boolean;
  /*private*/ _changes:{[key: string]:any};
  /*private*/ _expr_0:any;
  constructor() {
    this._changed = false;
    this._changes = {};
    this.context = new import0.InfiniteChartComponent();
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_input(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.input = currValue;
      this._changes['input'] = new import1.SimpleChange(this._expr_0,currValue);
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) {
      if (changed) {
        this.context.ngOnChanges(this._changes);
        this._changes = {};
      }
      if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); }
    }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_InfiniteChartComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_InfiniteChartComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.InfiniteChartComponent>;
  _ComponentFactoryResolver_0_3:any;
  _InfiniteChartComponent_0_4:Wrapper_InfiniteChartComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_InfiniteChartComponent_Host0,renderType_InfiniteChartComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'infinite-chart',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_InfiniteChartComponent0(this.viewUtils,this,0,this._el_0);
    this._ComponentFactoryResolver_0_3 = new import8.CodegenComponentFactoryResolver([import9.InfiniteChartSubComponentNgFactory],this.injectorGet(import8.ComponentFactoryResolver,this.parentIndex));
    this._InfiniteChartComponent_0_4 = new Wrapper_InfiniteChartComponent();
    this.compView_0.create(this._InfiniteChartComponent_0_4.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._InfiniteChartComponent_0_4.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import8.ComponentFactoryResolver) && (0 === requestNodeIndex))) { return this._ComponentFactoryResolver_0_3; }
    if (((token === import0.InfiniteChartComponent) && (0 === requestNodeIndex))) { return this._InfiniteChartComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._InfiniteChartComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const InfiniteChartComponentNgFactory:import7.ComponentFactory<import0.InfiniteChartComponent> = new import7.ComponentFactory<import0.InfiniteChartComponent>('infinite-chart',View_InfiniteChartComponent_Host0,import0.InfiniteChartComponent);
const styles_InfiniteChartComponent:any[] = ([] as any[]);
var renderType_InfiniteChartComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_InfiniteChartComponent,{});
export class View_InfiniteChartComponent0 extends import2.AppView<import0.InfiniteChartComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  compView_7:import2.AppView<import10.InfiniteChartSubComponent>;
  _InfiniteChartSubComponent_7_3:import9.Wrapper_InfiniteChartSubComponent;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_InfiniteChartComponent0,renderType_InfiniteChartComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,':xmlns:xhtml','http://www.w3.org/1999/xhtml'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,':svg:svg',new import3.InlineArray2(2,':xmlns:svg','http://www.w3.org/2000/svg'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._text_5 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._text_6 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_3,':svg:g',new import3.InlineArray2(2,'infinite-sub',''),(null as any));
    this.compView_7 = new import9.View_InfiniteChartSubComponent0(this.viewUtils,this,7,this._el_7);
    this._InfiniteChartSubComponent_7_3 = new import9.Wrapper_InfiniteChartSubComponent();
    this.compView_7.create(this._InfiniteChartSubComponent_7_3.context);
    this._text_8 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.InfiniteChartSubComponent) && (7 === requestNodeIndex))) { return this._InfiniteChartSubComponent_7_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._InfiniteChartSubComponent_7_3.ngDoCheck(this,this._el_7,throwOnChange);
    this.compView_7.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_7.destroy();
    this._InfiniteChartSubComponent_7_3.ngOnDestroy();
  }
}