/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../src/infinite-chart.module';
import * as import2 from '@angular/core/src/di/injector';
class InfiniteChartModuleInjector extends import0.NgModuleInjector<import1.InfiniteChartModule> {
  _InfiniteChartModule_0:import1.InfiniteChartModule;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.InfiniteChartModule {
    this._InfiniteChartModule_0 = new import1.InfiniteChartModule();
    return this._InfiniteChartModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.InfiniteChartModule)) { return this._InfiniteChartModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const InfiniteChartModuleNgFactory:import0.NgModuleFactory<import1.InfiniteChartModule> = new import0.NgModuleFactory(InfiniteChartModuleInjector,import1.InfiniteChartModule);